[features]
seeds = false
skip-lint = false

[programs.localnet]
asset_tokenization = "EjLLVvxkMtssALhHv4dvKhkxYJQKGmMUcB38DboGMYtJ"

[programs.devnet]
asset_tokenization = "EjLLVvxkMtssALhHv4dvKhkxYJQKGmMUcB38DboGMYtJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun test ./tests/"

[toolchain]
anchor_version = "0.32.1"