[features]
seeds = false
skip-lint = false

[programs.localnet]
asset_tokenization = "EjLLVvxkMtssALhHv4dvKhkxYJQKGmMUcB38DboGMYtJ"

[programs.devnet]
asset_tokenization = "EjLLVvxkMtssALhHv4dvKhkxYJQKGmMUcB38DboGMYtJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 20000

[scripts]
test = "bun test ./tests/"

[toolchain]
anchor_version = "0.32.1"
package_manager = "bun"
